config/routes.rb
AddressBook::Application.routes.draw do
  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
respond_to :html, :js
  def index
    @entries = Entry.all
    @entry = Entry.new


  end

  # GET /entries/1
  # GET /entries/1.json
#  def show
#    @entry = Entry.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @entry }
#    end
#  end
#
#  # GET /entries/new
#  # GET /entries/new.json
#  def new
#    @entry = Entry.new
#
#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @entry }
#    end
#  end
#
#  # GET /entries/1/edit
#  def edit
#    @entry = Entry.find(params[:id])
#  end
#
#  # POST /entries
#  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

      if @entry.save
            respond_with @entry, :location => entries_url
      end
  end
#
#  # PUT /entries/1
#  # PUT /entries/1.json
#  def update
#    @entry = Entry.find(params[:id])
#
#    respond_to do |format|
#      if @entry.update_attributes(params[:entry])
#        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
#        format.json { head :ok }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @entry.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
      respond_with @entry, :location => entries_url
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id=<%= dom_id(entry)%> class="entry">


 <%= entry.name %>
<%= entry.address %>
<%=entry.phone%>
  <%=entry.email%>
    <%= link_to "Destroy", entry,:remote => true,  :confirm => "You Sure", :method => :delete %>
  

</div>

app/views/entries/_form.html.erb
<%= form_for(@entry, :remote => true) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>
<table> 
  <tr>
  <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
    </tr>
</table>

<div id="entries">
  <%= render @entries %>
</div>


<h3>Add your new entry:</h3>

<%= render 'form' %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entry.name %>
</p>

<p>
  <b>Address:</b>
  <%= @entry.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @entry.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @entry.email %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>